{% set name = "pyqtads" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: bafea43b4902bd6b42004ef22ab682927e1e67d2ff4512b6d0c92a87d1997c5b
  patches:
    - 0001-setup.patch
    - 0002-sip_and_setup.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pyqt >=5.9
    - qt 5.12.*
    - setuptools
    - sip >=4.19
  run:
    - python
    - pyqt >=5.9
    - pywin32   # [win]
    - qt 5.12.*
    - sip >=4.19

test:
  imports:
    - PyQtAds

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPLv2+ 
  license_family: LGPL 
  license_file: LICENSE.md
  summary: 'Advanced Docking System for Qt'

  description: 'Advanced Docking System for Qt' 
  dev_url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
