{% set name = "pyqtads" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: d7c244d9accaa78766e90124c0ce6054327b78625dae8ba2cfe22fc29dfba37d
  patches:
    - 0001-4.3.0.patch

build:
  number: 0
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - jom                            # [win]
  host:
    - pyqt-builder
    - setuptools
    - python
    - pyqt
    - sip
    - qt5-advanced-docking-system
    - qt-main
    - xorg-libxfixes                 # [linux]
  run:
    - python
    - pyqt

test:
  imports:
    - PyQtAds

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Advanced Docking System for Qt
  description: Advanced Docking System for Qt
  dev_url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - klauer
    - n-elie
