{% set name = "pyqtads" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: 1c3f275efb90da41d076ca1118aaaaeb6649536f829fac0af4c7a8b574001e8b
  patches:
    - 0001-setup.patch
    - 0002-hotfix_for_3.3.0.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pyqt 5.12.*
    - qt 5.12.*
    - setuptools
    - sip >=4.19
  run:
    - python
    - pyqt 5.12.*
    - pywin32   # [win]
    - qt 5.12.*
    - sip >=4.19

test:
  imports:
    - PyQtAds

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPLv2+
  license_family: LGPL
  license_file: LICENSE
  summary: Advanced Docking System for Qt
  description: Advanced Docking System for Qt
  dev_url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
    - n-elie
