{% set name = "pyqtads" %}
{% set version = "3.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: 1f40bcabd8b2749ec85c2f9dd3d0110c08ef36331da81e624158362f7c201ffb
  patches:
    - 0001-setup.patch
    - 0002-3.7.2.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - python
    - pip
    - pyqt 5.12.*
    - qt 5.12.*
    - setuptools
    - xorg-libxfixes  # [linux]
  run:
    - python
    - pyqt 5.12.*
    - pywin32   # [win]
    - qt 5.12.*

test:
  imports:
    - PyQtAds.QtAds

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPLv2+
  license_family: LGPL
  license_file: LICENSE
  summary: Advanced Docking System for Qt
  description: Advanced Docking System for Qt
  dev_url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - klauer
    - n-elie
